# Generated by Django 5.0.1 on 2024-01-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='pilk-default.jpg', upload_to='pilk/location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pilkapi.location')),
            ],
        ),
        migrations.CreateModel(
            name='Pilk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='pilk-default.jpg', upload_to='pilk/items')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pilkapi.location')),
            ],
        ),
    ]
